---

- name: Create the ruler user and the company db
  postgresql_user:
    name: ruler
    state: present
    password: ruler@123
    encrypted: true
    login_user: postgres
    login_password: postgres
    comment: create the ruler user and the company db
  tags:
    - create-user
    - create-user-db-table

- name: Create the company db
  postgresql_db:
    name: rodaroda
    state: present
    login_user: postgres
    login_password: postgres
    login_unix_socket: /var/run/postgresql/
    owner: ruler
    template: template0
    encoding: UTF-8
  tags:
    - create-db
    - create-user-db-table

- name: Create the Locality table with some columns
  postgresql_table:
    db: rodaroda
    table: locality
    state: present
    login_user: postgres
    login_password: postgres
    owner: ruler
    login_unix_socket: /var/run/postgresql/
    columns:
      - id serial primary key
      - name varchar(100) not null
      - type varchar(100) check (type in ('origin', 'destination')) not null
  tags:
    - create-table
    - create-user-db-table

- name: Create the Product table
  postgresql_table:
    db: rodaroda
    table: product
    state: present
    login_user: postgres
    login_password: postgres
    columns:
      - id serial primary key
      - name varchar(100) not null
      - description text not null
  tags:
    - create-table

- name: Create the Carrier table
  postgresql_table:
    db: rodaroda
    table: carrier
    state: present
    login_user: postgres
    login_password: postgres
    columns:
      - id serial primary key
      - name varchar(100) not null
      - contact varchar(100) not null
  tags:
    - create-table

- name: Create the Vehicle table
  postgresql_table:
    db: rodaroda
    table: vehicle
    state: present
    login_user: postgres
    login_password: postgres
    columns:
      - id serial primary key
      - name varchar(100) not null
      - model varchar(100) not null
      - license_plate varchar(10) not null
  tags:
    - create-table

- name: Create the Trip table
  postgresql_table:
    db: rodaroda
    table: trip
    state: present
    login_user: postgres
    login_password: postgres
    columns:
      - id serial primary key
      - origin_id int references locality(id) on delete no action
      - destination_id int references locality(id) on delete no action
      - product_id int references product(id) on delete no action
      - carrier_id int references carrier(id) on delete no action
      - vehicle_id int references vehicle(id) on delete no action
      - leaving_date timestamp not null
      - arrival_date timestamp not null
  tags:
    - create-table
