---

- name: Create the ruler user and the company db
  postgresql_user:
    name: ruler
    state: present
    password: ruler@123
    encrypted: true
    login_user: postgres
    login_password: postgres
    comment: create the ruler user and the company db
  tags:
    - create-user
    - create-user-db-table

- name: Create the company db
  postgresql_db:
    name: company
    state: present
    login_user: postgres
    login_password: postgres
    login_unix_socket: /var/run/postgresql/
    owner: ruler
    template: template0
    encoding: UTF-8
  tags:
    - create-db
    - create-user-db-table

- name: Create the companies table with some columns
  postgresql_table:
    db: company
    table: companies
    state: present
    login_user: postgres
    login_password: postgres
    owner: ruler
    login_unix_socket: /var/run/postgresql/
    columns:
      - id bigserial primary key
      - name text
      - email text
      - cnpj bigint
      - employees integer
  tags:
    - create-table
    - create-user-db-table

- name: Create some companies data
  postgresql_query:
    db: company
    login_user: postgres
    login_password: postgres
    query: "INSERT INTO companies (name, email, cnpj, employees) VALUES ('{{ item.name }}', '{{ item.email }}', {{ item.cnpj }}, {{ item.employees }});"
  loop:
    - { name: 'Company 1', email: 'info@company1.com', cnpj: 111222333000144, employees: 110 }
    - { name: 'Company 2', email: 'info@company2.com', cnpj: 111222333000155, employees: 90 }
  tags:
    - create-data
    - create-user-db-table

- name: Calculates the avg employees quantity
  postgresql_query:
    db: company
    login_user: postgres
    login_password: postgres
    query: "SELECT AVG(employees) AS quantity_of_employees FROM companies;"
  register: query_result
  tags:
    - avg
    - create-user-db-table

- name: Prints the quantity of employees from all companies
  debug:
    var: query_result
  tags:
    - avg
    - create-user-db-table
