---

- name: Insert data into the Locality table
  postgresql_query:
    db: rodaroda
    login_user: postgres
    login_password: postgres
    query: "INSERT INTO locality (name, type) VALUES ('{{ item.name }}', '{{ item.type }}');"
  loop:
    - { name: 'Locality 1', type: 'origin' }
    - { name: 'Locality 2', type: 'destination' }
    - { name: 'Locality 3', type: 'origin' }
    - { name: 'Locality 4', type: 'destination' }
  tags:
    - create-data

- name: Insert data into the Product table
  postgresql_query:
    db: rodaroda
    login_user: postgres
    login_password: postgres
    query: "INSERT INTO product (name, description) VALUES ('{{ item.name }}', '{{ item.description }}');"
  loop:
    - { name: 'Product 1', description: 'Description 1' }
    - { name: 'Product 2', description: 'Description 2' }
  tags:
    - create-data

- name: Insert data into the Carrier table
  postgresql_query:
    db: rodaroda
    login_user: postgres
    login_password: postgres
    query: "INSERT INTO carrier (name, contact) VALUES ('{{ item.name }}', '{{ item.contact }}');"
  loop:
    - { name: 'Carrier 1', contact: 'Contact 1' }
    - { name: 'Carrier 2', contact: 'Contact 2' }
  tags:
    - create-data

- name: Insert data into the Vehicle table
  postgresql_query:
    db: rodaroda
    login_user: postgres
    login_password: postgres
    query: "INSERT INTO vehicle (name, model, license_plate) VALUES ('{{ item.name }}', '{{ item.model }}', '{{ item.license_plat }}');"
  loop:
    - { name: 'Vehicle 1', model: 'Model 1', license_plate: 'ABC0123' }
    - { name: 'Vehicle 2', model: 'Model 2', license_plate: 'XYZ0789' }
  tags:
    - create-data

- name: Insert data into the Trip table
  postgresql_query:
    db: rodaroda
    login_user: postgres
    login_password: postgres
    query: "INSERT INTO trip (origin_id, destination_id, product_id, carrier_id, vehicle_id, leaving_date, arrival_date) VALUES (1, 2, 1, 1, 1, '{{ item.leaving_date }}'::timestamp, '{{ item.arrival_date }}'::timestamp);"
  loop:
    - { leaving_date: '2023-01-01 08:00:00', arrival_date: '2024-01-01 16:00:00' }
    - { leaving_date: '2023-02-01 09:00:00', arrival_date: '2024-02-01 17:00:00' }
  tags:
    - create-data
