---

- name: debug info
  debug:
    #msg: "Host {{ ansible_hostname }} has {{ ansible_memtotal_mb }} MB Memory and {{ ansible_processor_cores }} CPU Cores."
    msg: "Suggested shared_buffers_size: {{ansible_memtotal_mb * 0.25}} and rounded  {{(ansible_memtotal_mb * 0.25)|int}} "

- name: Start postgres project with inline definition
  docker_container:
    image: postgres:{{ postgres_version | default('13') }}
    name: postgres
    volumes: /var/run/postgresql/:/var/run/postgresql
    env:
      POSTGRES_USER="postgres"
      POSTGRES_PASSWORD="postgres"
      POSTGRES_NAME="postgres"
    ports:
      - "5432:5432"
    state: started
    restart_policy: unless-stopped
    networks_cli_compatible: true

- name: Set postgres config
  community.general.postgresql_set:
    db: postgres
    login_host: localhost
    login_user: postgres
    login_password: postgres
    port: 5432
    name: "{{item.name}}"
    value: "{{item.value}}"
  with_items:
    - {name: 'shared_buffers', value: '{{postgres_shared_buffer}}'}
    - {name: 'max_connections', value: '{{postgres_max_connections}}'}
    - {name: 'work_mem', value: '{{postgres_work_mem}}'}
    - {name: 'maintenance_work_mem', value: '{{postgres_maintenance_work_mem}}'}
    - {name: 'effective_cache_size', value: '{{postgres_effective_cache_size}}'}
  register: setup_postgres

- name: restart postgres
  docker_container:
    name: postgres
    restart: yes
    state: started
  when: setup_postgres
